### ISSUE TITLE
FCL-DA: Sanitize filenames in Template Generation

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/BfROpenLab#507]
If the user tries to geerate backward or forward templates for stations which contains not allowed filename symbols the templates are not written to file system.

#### Solution: 
Remove linebreaks and illegal or not recommended symbols (`\\/:*?\"<>|#%&;'!@=+`) from filename.

**Comment by ruegenbfr** [comment]
Done!

To test this:
Use an existing station from the DB for which the generation of templates normally would succeed. Rename it within the DB-GUI by inserting the above mentioned symbols into the station name. Try to generate the template again.

**Comment by bfrgottscma** [comment]
Perfect. It is now possible to create forward/backward templates even when station names contain illegal/not recommended symbols. The file name of the new templates does not contain the special characters with regard to stations but in the template, the station name is still shown with the special characters to ensure consistency with the real name of the company. Done!
